<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пример сайта</title>
</head>
<body>
<header>
    <h1>Мой сайт</h1>
    <nav>
        <a href="/">Главная</a>
    </nav>
</header>

@content

<footer>
    <p>Посетите мой <a href="https://github.com/DEGTEVUWU">GitHub профиль</a></p>

</footer>
</body>
</html>